name: 部署文档

on:
  push:
    branches:
      - main
  workflow_dispatch: # 支援手動觸發

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 🎯 移除 version 属性，自动读取 package.json 中的 packageManager
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      # 🎯 放行构建脚本并安装依赖
      - name: 允许核心二进制档脚本并安装依赖
        run: |
          pnpm config set ignore-scripts false
          pnpm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist